// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/networkconnectivity/v1/hub.proto

package com.google.cloud.networkconnectivity.v1;

public interface RoutingVPCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.networkconnectivity.v1.RoutingVPC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The URI of a VPC network.
   * </pre>
   *
   * <code>string uri = 1 [(.google.api.resource_reference) = { ... }</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * The URI of a VPC network.
   * </pre>
   *
   * <code>string uri = 1 [(.google.api.resource_reference) = { ... }</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();
}
